import Carbon.HIToolbox

enum KeyCodeMap {
    private static let map: [UInt16: String] = [
        UInt16(kVK_ANSI_A): "A",
        UInt16(kVK_ANSI_S): "S",
        UInt16(kVK_ANSI_D): "D",
        UInt16(kVK_ANSI_F): "F",
        UInt16(kVK_ANSI_H): "H",
        UInt16(kVK_ANSI_G): "G",
        UInt16(kVK_ANSI_Z): "Z",
        UInt16(kVK_ANSI_X): "X",
        UInt16(kVK_ANSI_C): "C",
        UInt16(kVK_ANSI_V): "V",
        UInt16(kVK_ANSI_B): "B",
        UInt16(kVK_ANSI_Q): "Q",
        UInt16(kVK_ANSI_W): "W",
        UInt16(kVK_ANSI_E): "E",
        UInt16(kVK_ANSI_R): "R",
        UInt16(kVK_ANSI_Y): "Y",
        UInt16(kVK_ANSI_T): "T",
        UInt16(kVK_ANSI_1): "1",
        UInt16(kVK_ANSI_2): "2",
        UInt16(kVK_ANSI_3): "3",
        UInt16(kVK_ANSI_4): "4",
        UInt16(kVK_ANSI_6): "6",
        UInt16(kVK_ANSI_5): "5",
        UInt16(kVK_ANSI_Equal): "=",
        UInt16(kVK_ANSI_9): "9",
        UInt16(kVK_ANSI_7): "7",
        UInt16(kVK_ANSI_Minus): "-",
        UInt16(kVK_ANSI_8): "8",
        UInt16(kVK_ANSI_0): "0",
        UInt16(kVK_ANSI_RightBracket): "]",
        UInt16(kVK_ANSI_O): "O",
        UInt16(kVK_ANSI_U): "U",
        UInt16(kVK_ANSI_LeftBracket): "[",
        UInt16(kVK_ANSI_I): "I",
        UInt16(kVK_ANSI_P): "P",
        UInt16(kVK_ANSI_L): "L",
        UInt16(kVK_ANSI_J): "J",
        UInt16(kVK_ANSI_Quote): "'",
        UInt16(kVK_ANSI_K): "K",
        UInt16(kVK_ANSI_Semicolon): ";",
        UInt16(kVK_ANSI_Backslash): "\\",
        UInt16(kVK_ANSI_Comma): ",",
        UInt16(kVK_ANSI_Slash): "/",
        UInt16(kVK_ANSI_N): "N",
        UInt16(kVK_ANSI_M): "M",
        UInt16(kVK_ANSI_Period): ".",
        UInt16(kVK_ANSI_Grave): "`",
        UInt16(kVK_Return): "\u{21A9}",
        UInt16(kVK_Tab): "\u{21E5}",
        UInt16(kVK_Space): "Space",
        UInt16(kVK_Delete): "\u{232B}",
        UInt16(kVK_Escape): "\u{238B}",
        UInt16(kVK_ForwardDelete): "\u{2326}",
        UInt16(kVK_Home): "\u{2196}",
        UInt16(kVK_End): "\u{2198}",
        UInt16(kVK_PageUp): "\u{21DE}",
        UInt16(kVK_PageDown): "\u{21DF}",
        UInt16(kVK_LeftArrow): "\u{2190}",
        UInt16(kVK_RightArrow): "\u{2192}",
        UInt16(kVK_DownArrow): "\u{2193}",
        UInt16(kVK_UpArrow): "\u{2191}",
        UInt16(kVK_F1): "F1",
        UInt16(kVK_F2): "F2",
        UInt16(kVK_F3): "F3",
        UInt16(kVK_F4): "F4",
        UInt16(kVK_F5): "F5",
        UInt16(kVK_F6): "F6",
        UInt16(kVK_F7): "F7",
        UInt16(kVK_F8): "F8",
        UInt16(kVK_F9): "F9",
        UInt16(kVK_F10): "F10",
        UInt16(kVK_F11): "F11",
        UInt16(kVK_F12): "F12",
    ]

    static func nameForKeyCode(_ keyCode: UInt16) -> String {
        map[keyCode] ?? "Key\(keyCode)"
    }

    static func keyCodeForName(_ name: String) -> UInt16? {
        map.first { $0.value == name }?.key
    }
}
